<!DOCTYPE library[
  <!ELEMENT library(books,members,staff,publisher)>
      <!ELEMENT books(book1,book2)>
          <!ELEMENT book1(author,price,title,year,isbn)>
              <!ELEMENT author(#PCDATA)>
              <!ELEMENT price(#PCDATA)>
              <!ELEMENT title(#PCDATA)>
              <!ELEMENT year(#PCDATA)>
              <!ELEMENT isbn(#PCDATA)>
          <!ELEMENT book2(author,price,title,year,isbn)>
              <!ELEMENT author(#PCDATA)>
              <!ELEMENT price(#PCDATA)>
              <!ELEMENT title(#PCDATA)>
              <!ELEMENT year(#PCDATA)>
              <!ELEMENT isbn(#PCDATA)>
     <!ELEMENT members(member1,member2)>
            <!ELEMENT member1(name,address,phone number>
              <!ELEMENT name(#PCDATA)>
              <!ELEMENT address(#PCDATA)>
              <!ELEMENT phone number(#PCDATA)>
            <!ELEMENT member2(name,address,phone number>
              <!ELEMENT name(#PCDATA)>
              <!ELEMENT address(#PCDATA)>
              <!ELEMENT phone number(#PCDATA)>
     <!ELEMENT staffs(staff1,staff2)>
            <!ELEMENT staff1(name,address,phone number>
              <!ELEMENT name(#PCDATA)>
              <!ELEMENT address(#PCDATA)>
              <!ELEMENT phone number(#PCDATA)>
            <!ELEMENT staff2(name,address,phone number>
              <!ELEMENT name(#PCDATA)>
              <!ELEMENT address(#PCDATA)>
              <!ELEMENT phone number(#PCDATA)>
   
     <!ELEMENT publisher(publisher1,publisher2)>
            <!ELEMENT publisher1(name,address,phone number>
              <!ELEMENT name(#PCDATA)>
              <!ELEMENT address(#PCDATA)>
              <!ELEMENT phone number(#PCDATA)>
            <!ELEMENT publisher2(name,address,phone number>
              <!ELEMENT name(#PCDATA)>
              <!ELEMENT address(#PCDATA)>
              <!ELEMENT phone number(#PCDATA)>
 <!ATTLIST book1 bookid CDATA#REQUIRED>
<!ATTLIST book2 bookid CDATA#REQUIRED>
<!ATTLIST member1 memberid CDATA#REQUIRED>
<!ATTLIST member2 memberid CDATA#REQUIRED>
<!ATTLIST staff1 staffid CDATA#REQUIRED>
<!ATTLIST staff2 staffid CDATA#REQUIRED>
<!ATTLIST publisher publisid CDATA #REQUIRED>
]>           
<library>
  <books>
     <book1 bookid="1">
          <author>abc</author>
          <price>100</price>
          <title>WDT</title>
          <year>2000</year>
          <isbn>202-14</isbn>
     </book1>
     <book2 bookid="2">
          <author>abcd</author>
          <price>150</price>
          <title>WDT2</title>
          <year>2003</year>
          <isbn>202-15</isbn>
     </book2>
  <member>
      <member1 memberid="3">
         <name>bharathi</name>
         <address>narpala</address>
         <phone number>678905432</phone>
       </member1>
       <member2 memberid="4">
         <name>bhavana</name>
         <address>narpala</address>
         <phone number>678905678</phone number>
       </member2>
 </member>
  <staff>
      <staff1 staffid="5">
         <name>bhavana</name>
         <address>ATP</address>
         <phone number>678905432</phone>
      </staff1>
      <staff staffid="6">
         <name>bharathi</name>
         <address>narpala</address>
         <phone number>678905432</phone>
      </staff2>
 </staff>
  <publisher>
     <publisher1 publishid="6">
         <name>dhana</name>
         <address>ATP</address>
         <phone number>7207267553</phone>
     </publisher1>
     <publisher2 publishid="7">
         <name>deeepika</name>
         <address>kurnool</address>
         <phone number>7297267553</phone>
     </publisher2>
 </publisher>
</library>